# ── PWM（舵机核心依赖）──────────────────────────────
CONFIG_PWM=y
 
# ── GPIO（LEDC 引脚复用底层依赖，必须开启）──────────
CONFIG_GPIO=y
 
# ── 日志系统 ─────────────────────────────────────────
CONFIG_LOG=y
CONFIG_PRINTK=y
 
# ── 堆栈 ─────────────────────────────────────────────
CONFIG_MAIN_STACK_SIZE=2048
 
